### ISSUE TITLE
Move alias and magic file into i18n folder

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticSignup#5]
Follow-up to https://github.com/SemanticMediaWiki/SemanticSignup/issues/3#issuecomment-70755889
- SemanticSignup.i18n.aliases.php
- SemanticSignup.i18n.magic.php

**Comment by mwjames** [comment]
@kghbln FYI

**Comment by kghbln** [comment]
Ah yes. Shame on me. I forgot. :(

@siebrand Will it be possible to move files with the translations for the e.g. aliases and namespaces (not this extension though) into the i18n folder without breaking the process with translatewiki.net?

**Comment by siebrand** [comment]
Yes, that's possible. Please ping @raymondde when you do that, as we need to update some configuration in mediawiki-extensions.txt for translatewiki.net. I'm not a fan, though, because I think that we should integrate the contents of the mentioned files in the JSON files, and not add PHP files in that folder. There are no technical reasons to not do it, though.

**Comment by kghbln** [comment]
Thank you for your info and insight!

**Comment by mwjames** [comment]
>  though, because I think that we should integrate the contents of the mentioned files in the JSON files, and not add PHP files in that folder. There are no technical reasons to not do it, though.

If at some point alias/magic arrays get integrated into JSON then this is fine but i18n belongs in its respective folder and not into the root directory.
